catalog/urls.py
from django.conf.urls import url
from catalog import views

urlpatterns = [
    url(r'^category/(?P<url_pretty>\w+)/$', views.category, name='category'),
    url(r'^catalog/(?P<url_pretty>\w+)/$', views.catalog, name='catalog'),
    url(r'^load_content/(?P<url_pretty>\w+)/', views.load_content, name='load_content'),
    url(r'^send_mail/', views.send_mail, name='send_mail')
]

portfolio/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^', include('web.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
]

web/urls.py
from django.conf.urls import url, include
from web import views

urlpatterns = [
    url(r'^$', views.site, name='site'),
    url(r'^', include('catalog.urls'))
]

catalog/models.py
from django.db import models
from tinymce.models import HTMLField
from django.db.models.signals import post_save


class Category(models.Model):
    index_title = models.TextField(max_length=256, blank=True, null=True, default=None,
                                   verbose_name=u"Заголовок на главной")
    first_title = HTMLField(default=None, verbose_name=u"Заголовок первого экрана")
    first_text = HTMLField(default=None, verbose_name=u"Текст на первом экране")
    second_title = models.TextField(max_length=256, blank=True, null=True, default=None,
                                   verbose_name=u"Заголовок второго экрана")
    third_title = models.TextField(max_length=256, blank=True, null=True, default=None,
                                   verbose_name=u"Заголовок экрана с консультацией")
    meta_tags = models.TextField(max_length=256, blank=True, null=True, default=None,
                                   verbose_name=u"Мета теги страницы")
    url_pretty = models.CharField(max_length=256, blank=True, null=True, default=None,
                                   verbose_name=u"URL")
    catalog_url = models.CharField(max_length=556, blank=True, null=True, default=None,
                                   verbose_name=u"Ссылка на каталог")

    def __str__(self):
        return '%s' % self.index_title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class CategoryIndexImg(models.Model):
    service = models.ForeignKey(Category, blank=True, null=True, default=None, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='static/img/categories', verbose_name=u"Фото на главной")

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Фото на главной'
        verbose_name_plural = 'Фото на главной'


class CategoryInnerImg(models.Model):
    service = models.ForeignKey(Category, blank=True, null=True, default=None, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='static/img/categories', verbose_name=u"Фото на первом экране")

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Фото на первом экране'
        verbose_name_plural = 'Фото на первом экране'


class CategoryCatalogImg(models.Model):
    service = models.ForeignKey(Category, blank=True, null=True, default=None, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='static/img/categories', verbose_name=u"Фото каталога")

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Фото каталога'
        verbose_name_plural = 'Фото каталога'


class CategoryCatalogText(models.Model):
    service = models.ForeignKey(Category, blank=True, null=True, default=None, on_delete=models.CASCADE)
    text = HTMLField(default=None, verbose_name=u"Пункт каталога")

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Пункт каталога'
        verbose_name_plural = 'Пункты каталога'


class CategoryConsImg(models.Model):
    service = models.ForeignKey(Category, blank=True, null=True, default=None, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='static/img/categories', verbose_name=u"Фото консультация")

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Фото консультация'
        verbose_name_plural = 'Фото консультации'


class CategoryConsText(models.Model):
    service = models.ForeignKey(Category, blank=True, null=True, default=None, on_delete=models.CASCADE)
    text = HTMLField(default=None, verbose_name=u"Пункт консултации")

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Пункт консултации'
        verbose_name_plural = 'Пункты консультации'


class Product(models.Model):
    category = models.ForeignKey(Category, blank=True, null=True, default=None, on_delete=models.CASCADE,
                                 verbose_name=u"Категория")
    date = models.CharField(max_length=126, blank=True, null=True, default=None,
                            verbose_name=u"Дата изготовления")
    title = models.CharField(max_length=256, blank=True, null=True, default=None,
                            verbose_name=u"Заголовок")
    text = HTMLField(default=None, verbose_name=u"Описание")
    type = models.CharField(max_length=10, blank=True, null=True, default=None)

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class ProductImg(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='static/img/categories', verbose_name=u"Фото изделия")
    type = models.CharField(max_length=10, blank=True, null=True, default=None)

    def __str__(self):
        return '%s' % self.id

    class Meta:
        verbose_name = 'Фото изделия'
        verbose_name_plural = 'Фото изделия'

    def save(self, *args, **kwargs):
        if self.img.width >= self.img.height:
            self.type = '1'
        else:
            self.type = '2'
        super(ProductImg, self).save(*args, **kwargs)


# изменение типа карточки продукта, при разных изображениях
def product_type_post_save(sender, instance, created, **kwargs):
    product = instance.product
    images = ProductImg.objects.filter(product_id=instance.product_id)

    wide = 0
    tall = 0

    for i in images:
        if i.img.width >= i.img.height:
            wide += 1
        elif i.img.width < i.img.height:
            tall += 1

    if wide >= 2 and tall == 0:
        instance.product.type = 1
    elif tall >= 2 and wide == 0:
        instance.product.type = 2
    elif wide >= 2 and tall >= 1:
        instance.product.type = 3
    else:
        instance.product.type = 1

    instance.product.save(force_update=True)


post_save.connect(product_type_post_save, sender=ProductImg)

catalog/views.py
from django.shortcuts import render
from catalog.models import *
from django.http import HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import EmailMessage


def category(request, url_pretty):
    category_cur = Category.objects.get(url_pretty=url_pretty)
    products = category_cur.product_set.all()[:5]
    return render(request, 'site/inner.html', locals())


def catalog(request, url_pretty):
    category_cur = Category.objects.get(url_pretty=url_pretty)
    products = category_cur.product_set.all()[:2]
    return render(request, 'site/detail.html', locals())


@csrf_exempt
def load_content(request, url_pretty):
    r = request.POST

    try:
        i = int(r.get('item')) + 1
        product = Category.objects.get(url_pretty=url_pretty).product_set.all()[i]

        return HttpResponse(render(request, 'site/catalog.html', locals()), content_type='text/plain')

    except:

        return JsonResponse(r)


def send_mail(request):
    r = request.POST

    if len(r) != 0:
        name = r.get('name')
        phone = r.get('phone')
        type = r.get('type')
        text = ''
        msg = '{}\nИмя: {}\nТелефон: {}'.format(type, name, phone)
        if 'text' in r and len(r.get('text')) != 0:
            text = r.get('text')
            msg = msg + '\nГород: {}'.format(text)

        email = EmailMessage(type, msg, to=['marukhelin@gmail.com'])
        email.send()

    return JsonResponse(r)

templates/site/catalog.html
    {% if product.type == '1' %}
    <div class="inner-item-detail" data-item="{% if i %}{{ i }}{% else %}{{ forloop.counter0 }}{% endif %}">
        <div class="inner-item__top clearfix">
            <h4>Проект был изготовлен: <span>{{ product.date }}</span></h4>
            <button data-type="Стоимость {{ product.title }}" class="get-price">Узнать стоимость</button>
        </div>
        <div class="inner-item-wrapper clearfix">
            <div class="inner-item__images inner-images-type1 clearfix">
                {% for img in product.productimg_set.all %}
                <div class="inner-image__wrap">
                    <a href="/{{ img.img.url }}" data-lightbox="{{ product.id }}">
                        <img src="/{{ img.img.url }}" alt=""/>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="inner-item__text inner-text-type1">
                <h5>{{ product.title }}</h5>
                <p>{{ product.text|safe }}</p>
            </div>
        </div>
    </div>
    {% elif product.type == '2' %}
    <div class="inner-item-detail" data-item="{% if i %}{{ i }}{% else %}{{ forloop.counter0 }}{% endif %}">
        <div class="inner-item__top clearfix">
            <h4>Проект был изготовлен: <span>{{ product.date }}</span></h4>
            <button data-type="Стоимость {{ product.title }}" class="get-price undertitle">Узнать стоимость</button>
        </div>
        <div class="inner-item-wrapper clearfix">
            <div class="inner-item__images inner-images-type2 clearfix">
                {% for img in product.productimg_set.all %}
                <div class="inner-image__wrap">
                    <a href="/{{ img.img.url }}" data-lightbox="{{ product.id }}">
                        <img src="/{{ img.img.url }}" alt=""/>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="inner-item__text inner-text-type2">
                <h5>{{ product.title }}</h5>
                <p>{{ product.text|safe }}</p>
            </div>
        </div>
    </div>
    {% elif product.type == '3' %}
    <div class="inner-item-detail" data-item="{% if i %}{{ i }}{% else %}{{ forloop.counter0 }}{% endif %}">
        <div class="inner-item__top clearfix">
            <h4>Проект был изготовлен: <span>{{ product.date }}</span></h4>
            <button data-type="Стоимость {{ product.title }}" class="get-price undertitle">Узнать стоимость</button>
        </div>
        <div class="inner-item-wrapper clearfix">
            <div class="inner-item__images inner-images-type3 clearfix">
                {% for img in product.productimg_set.all %}
                <div class="inner-image__wrap{% if img.type == '2' %} inner-image-right{% endif %}{% if img.type == '1' %} inner-image-left{% endif %}">
                    <a href="/{{ img.img.url }}" data-lightbox="{{ product.id }}">
                        <img src="/{{ img.img.url }}" alt=""/>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="inner-item__text inner-text-type2">
                <h5>{{ product.title }}</h5>
                <p>{{ product.text|safe }}</p>
            </div>
        </div>
    </div>
    {% endif %}

templates/site/inner.html
{% load static %}
<!DOCTYPE html>
<html lang="en"></html>
<head>
	<meta charset="UTF-8"/>
	<title>{{ category_cur.index_title }}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<link rel="stylesheet" href="{% static 'libs/bootstrap/bootstrap-grid-3.3.1.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'libs/font-awesome-4.7.0/css/font-awesome.min.css' %}"/>
	<link href="{% static 'libs/owl-carousel/owl.carousel.css' %}" rel="stylesheet"/>
	<link href="{% static 'css/fonts.css' %}" rel="stylesheet"/>
	<link href="{% static 'css/normalize.css' %}" rel="stylesheet"/>
	<link href="{% static 'libs/jquery-nice-select-1.1.0/css/nice-select.css' %}" rel="stylesheet"/>
	<link href="{% static 'css/lightbox.css' %}" rel="stylesheet"/>
	<link href="{% static 'css/main.css' %}" rel="stylesheet"/>
	<link href="{% static 'css/media.css' %}" rel="stylesheet"/>
</head>
<body>
	<header>
		<div class="container">
			<div class="head-flex">
				<div class="head-left clearfix">
                    <a href="/"><img src="{% static 'img/logo.png' %}"/></a>
					<h2>Изделия для вашего интерьера<br>Подбор, изготовление, установка</h2>
				</div>
				<div class="head-right clearfix">
					<button class="callback">Заказать звонок</button>
					<p><span>Есть вопросы?<br></span>+7 (812) 213-21-22</p>
				</div>
			</div>
		</div>
		<nav>
			<div class="container"><img src="{% static 'img/burger.png' %}" class="burger-menu xs-mob"/>
				<ul>
					<li><a id="a1" href="">Готовые изделия</a></li>
					<li><a id="a2" href="">О компании</a></li>
					<li><a id="a3" href="">Услуги</a></li>
					<li><a id="a4" href="">Каталог</a></li>
					<li><a id="a5" href="">Наше производство</a></li>
					<li><a id="a6" href="">Отзывы</a></li>
					<li><a id="a7" href="#contacts">Контакты</a></li>
				</ul>
			</div>
		</nav>
	</header>
	<section class="inner-main">
		<div class="container">
			<div class="inner-main__left">
                <img src="/{{ category_cur.categoryinnerimg_set.first.img.url }}" class="inner-main__bg"/>
				<h2>{{ category_cur.first_title|safe }}</h2>
				<div class="line"></div>
			</div>
			<div class="inner-main__right">
				<p>{{ category_cur.first_text|safe }}</p>
			</div>
		</div>
	</section>
	<div class="container inner-advances-wrap">
		<div class="inner-advances">
			<div class="advances-item">
				<h4>Полный цикл работ</h4><img src="{% static 'img/a1.png' %}"/>
				<p>Полный цикл работ,<br>замер, доставка,<br>установка</p>
			</div>
			<div class="advances-item">
				<h4>Подбор материалов</h4><img src="{% static 'img/a2.png' %}"/>
				<p>Подбор материалов<br>под интерьер </p>
			</div>
			<div class="advances-item">
				<h4>Экономия</h4><img src="{% static 'img/a3.png' %}"/>
				<p>Экономия до 50%<br>за счёт производства</p>
			</div>
			<div class="advances-item">
				<h4>Бесплатный замер</h4><img src="{% static 'img/a4.png' %}"/>
				<p>Бесплатный замер<br>в день обращения</p>
			</div>
			<div class="advances-item">
				<h4>Гарантия 1 год</h4><img src="{% static 'img/a5.png' %}"/>
				<p>Потому что уверены<br>в качестве</p>
			</div>
		</div>
	</div>
	<section class="inner-block">
		<div class="container">
			<h2>{{ category_cur.second_title }}</h2>
			<div class="inner-slider">
				<div class="inner-slider__wrap">
					<div class="inner-slider__container clearfix">
						{% for image in products %}
						<div class="inner-item {% if forloop.counter0 == 1 %}central{% endif %}">
                            <img src="/{{ image.productimg_set.first.img.url }}"/>
							<div class="main-item__detail"><span>Узнать подробнее</span><img src="{% static 'img/zoom.png' %}"/></div>
						</div>
                        {% endfor %}
					</div>
				</div>
				<div class="inner-prev"><img src="{% static 'img/arr-prev.png' %}"/></div>
				<div class="inner-next"><img src="{% static 'img/arr-next.png' %}"/></div>
			</div><a href="{% url 'catalog' category_cur.url_pretty %}" target="_blank" class="more-button">Смотреть больше наших проектов</a>
		</div>
	</section>
	<section class="main-catalog">
		<div class="container">
			<h2>Посмотрите полный каталог с готовыми изделиями и материалами</h2>
			<div class="main-catalog__block clearfix">
                <img src="/{{ category_cur.categorycatalogimg_set.first.img.url }}"/>
				<div class="main-catalog__right">
					<h5>В каталоге вы найдете:</h5>
					<ul>
                        {% for li in category_cur.categorycatalogtext_set.all %}
						<li>{{ li.text|safe }}</li>
                        {% endfor %}
					</ul>
					<a class="download" href="{{ category_cur.catalog_url }}" target="_blank">Смотреть каталог</a>
				</div>
			</div>
		</div>
	</section>
	<section class="inner-video">
		<div class="container">
			<h2>Мы гарантируем вам фабричное качество и фабричные цены!</h2>
			<div class="inner-video__block clearfix">
				<div class="inner-video__left">
					<h5>Опыт работы</h5>
					<p>Все работники цеха, мастера 3 и 4 разряда с опытом работы в нашей компании, более 5 лет. 5 лет.</p>
					<h5>Оборудование</h5>
					<p>Более 1000 м² складских территорий, отлаженная логистика и современный парк оборудования - это гарантия того, что Вы получите изделия хорошего качества.</p>
					<h5>Компетентные сотрудники</h5>
					<p>Мы дорожим Вашим доверием и своей репутацией, поэтому от консультации и замера, до изготовления и установки изделий у Вас дома, Вас будут обслуживать вежливые и грамотные специалисты</p>
				</div>
				<div class="inner-video__right"><img src="{% static 'img/v.png' %}" class="screen"/><img src="{% static 'img/play-btn.png' %}" class="video-play"/></div>
			</div>
		</div>
	</section>
	<section class="consultation">
		<div class="consultation__img-wrap">
            <img src="/{{ category_cur.categoryconsimg_set.first.img.url }}"/></div>
		<div class="container">
			<div class="consultation__form">
				<h2>Закажите бесплатную консультацию<br>нашего специалиста</h2>
				<div class="line"></div>
				<p>Закажите консультацию специалиста</p>
				<ul>
                    {% for li in category_cur.categoryconstext_set.all %}
					<li>{{ li.text }}</li>
                    {% endfor %}
				</ul>
				<form>
					<div class="half">
						<div>
							<label>Введите имя</label>
							<input type="text" name="name" required="required"/>
						</div>
						<div>
							<label>Введите телефон</label>
							<input type="text" name="phone" required="required"/>
						</div>
					</div>
					<label>Ваши пожелания</label>
					<textarea name="text"></textarea>
					<button>Заказать консультацию</button>
                    <input type="hidden" name="type" value="{{ category_cur.index_title }} - Заявка на консультацию">
                    {% csrf_token %}
				</form>
			</div>
		</div>
	</section>
	<section class="map" id="contacts">
		<div class="map__block">
			<div class="container map__container">
				<div class="map__adress">
					<h3>Адрес офиса:</h3>
					<ul>
						<li>ул. Магнитогорская дом 17-21, центр мебельных комплектующих "Макмарт"</li>
					</ul><br/>
					<h3>Адреса филиала:</h3>
					<ul>
						<li>ул. Химиков дом 26, центр мебельных комплектующих Прогресс М</li>
					</ul><br/>
					<h3>Адреса производства:</h3>
					<ul>
						<li>Глухоозерское шоссе дом 12, территория "Завода "Молодой Ударник"</li>
					</ul><br/>
					<p>Телефон: +7 (812) 426-92-93 (многоканальный)<br>Отдел приема заказов: нажмите 2 (добавочный 101)<br>Факс: нажмите 1 (добавочный 102)<br>Почта: zakaz-od@mail.ru	</p>
				</div>
			</div>
			<div class="map__cont"><script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A661d9ea720de060c5ddb3d3b06d9dba747a322a33aa38e826c0fd1282ede1309&amp;width=100%25&amp;height=100%&amp;lang=ru_RU&amp;scroll=true"></script></div>
		</div>
	</section>
	<footer>
		<div class="container">
			<div class="footer-flex">
				<div class="clearfix footer-left"><img src="{% static 'img/logo.png' %}" class="logo"/>
					<h4>Изделия для вашего интерьера<br>Подбор, изготовление, установка</h4>
				</div>
				<div class="clearfix footer-right">
					<p class="hrefs"><a href=''>© «Омега-Дизайн» 2017</a> <a href=''>Политика конфиденциальности</a></p>
					<p class="corp">Над структурой и дизайном работал <a href=''>Бояршинов Данил</a></p>
				</div>
			</div>
		</div>
	</footer>
	<div class="layer">
		<div class="popup-min callback-popup"><img src="{% static 'img/cross.png' %}" class="close"/>
			<h3>Заявка на обратный звонок</h3>
			<div class="line"></div>
			<p>Заполните поля ниже и наш специалист свяжется с вами в течение 10 минут.</p>
			<form>
				<input type="text" placeholder="Введите имя" name="name" required="required"/>
				<input type="text" placeholder="Введите телефон" name="phone" required="required"/>
				<textarea name="text" placeholder="Ваши комментарии"></textarea>
				<button>Заказать звонок</button>
                {% csrf_token %}
                <input type="hidden" name="type" value="Заявка на обратный звонок">
			</form>
		</div>
        {% for product in products %}
            {% if product.type == '1' %}
            <div class="inner-item-detail centered-popup">
                <div class="inner-item__top clearfix">
                    <h4>Проект был изготовлен: <span>{{ product.date }}</span></h4>
                    <button data-type="Стоимость {{ product.title }}" class="get-price">Узнать стоимость</button>
                </div>
                <div class="inner-item-wrapper clearfix">
                    <div class="inner-item__images inner-images-type1 clearfix">
                        {% for img in product.productimg_set.all %}
                        <div class="inner-image__wrap">
                            <a href="/{{ img.img.url }}" data-lightbox="{{ product.id }}">
                                <img src="/{{ img.img.url }}" alt=""/>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="inner-item__text inner-text-type1">
                        <h5>{{ product.title }}</h5>
                        <p>{{ product.text|safe }}</p>
                    </div>
                </div>
            </div>
            {% elif product.type == '2' %}
            <div class="inner-item-detail centered-popup">
				<div class="inner-item__top clearfix">
					<h4>Проект был изготовлен: <span>{{ product.date }}</span></h4>
					<button data-type="Стоимость {{ product.title }}" class="get-price undertitle">Узнать стоимость</button>
				</div>
				<div class="inner-item-wrapper clearfix">
					<div class="inner-item__images inner-images-type2 clearfix">
                        {% for img in product.productimg_set.all %}
						<div class="inner-image__wrap">
                            <a href="/{{ img.img.url }}" data-lightbox="{{ product.id }}">
                                <img src="/{{ img.img.url }}" alt=""/>
                            </a>
                        </div>
                        {% endfor %}
					</div>
					<div class="inner-item__text inner-text-type2">
						<h5>{{ product.title }}</h5>
						<p>{{ product.text|safe }}</p>
					</div>
				</div>
			</div>
            {% elif product.type == '3' %}
            <div class="inner-item-detail centered-popup">
				<div class="inner-item__top clearfix">
					<h4>Проект был изготовлен: <span>{{ product.date }}</span></h4>
					<button data-type="Стоимость {{ product.title }}" class="get-price undertitle">Узнать стоимость</button>
				</div>
				<div class="inner-item-wrapper clearfix">
					<div class="inner-item__images inner-images-type3 clearfix">
                        {% for img in product.productimg_set.all %}
						<div class="inner-image__wrap{% if img.type == '2' %} inner-image-right{% endif %}{% if img.type == '1' %} inner-image-left{% endif %}">
                            <a href="/{{ img.img.url }}" data-lightbox="{{ product.id }}">
                                <img src="/{{ img.img.url }}" alt=""/>
                            </a>
                        </div>
                        {% endfor %}
					</div>
					<div class="inner-item__text inner-text-type2">
						<h5>{{ product.title }}</h5>
						<p>{{ product.text|safe }}</p>
					</div>
				</div>
			</div>
            {% endif %}
        {% endfor %}
		<div class="popup-min popup-price"><img src="{% static 'img/cross.png' %}" class="close"/>
			<h3>Узнать стоимость</h3>
			<div class="line"></div>
			<p>Заполните поля ниже, и мы отправим вам стоимость изделий по смс.</p>
			<form>
				<input type="text" placeholder="Введите имя" name="name" required="required"/>
				<input type="text" placeholder="Введите телефон" name="phone" required="required"/>
				<input type="hidden" name="type"/>
				<button>Узнать стоимость </button>
                {% csrf_token %}
			</form>
		</div>
	</div>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script src="{% static 'libs/scrollto/jquery.scrollTo.min.js' %}"></script>
	<script src="{% static 'libs/owl-carousel/owl.carousel.js' %}"></script>
	<script src="{% static 'libs/jquery-nice-select-1.1.0/js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'js/lightbox.js' %}"></script>
	<script src="{% static 'js/mask.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>